A simple cmake file & fix compile error on gcc11
50C4L/portal-cpp-opengl pull request #1
Opened 2021-12-24 03:16 UTC by carlcc

1. 增加了一个简单的cmakelists.txt支持使用cmake构建（因为我的电脑是linux系统，用不了vs项目）。
2. 解决了linux下编译不通过的问题。

唔……我的电脑是 AMD Ryzen 7 PRO 4750U + 它的核心显卡，运行起来效果不太稳定的样子

2021-12-24 11:48 UTC, 50C4L requested changes
谢谢加上了CMake
最近有时间我会写个readme和依赖列表

2021-12-24 11:48 UTC, 50C4L commented on Renderer.cpp
> -#include <stb_image.h>
`stb_image.h` 是个第三方库（只有头文件），这里不用双引号因为那个文件一般不在同一个目录下

2021-12-24 12:03 UTC, carlcc commented on Renderer.cpp
> -#include <stb_image.h>
嗯，我知道，主要是你项目里没带上，而stb一般也没有单独的安装包，所以直接加项目里了。
另外因为你的项目没有分目录，就直接跟其他文件放同一层了，如果你觉得有必要改的话我晚点再给你改了

2021-12-24 12:05 UTC, 50C4L commented on Renderer.cpp
> -#include <stb_image.h>
好的麻烦了，其实是有个thirdparty的目录的，但是我没时间弄license所以没传上来，过几天有空我加上去

2021-12-25 10:31 UTC, 50C4L approved these changes

2022-01-13 11:24 UTC, merged